#include "../include/logger.h"
#include <stdarg.h>
#include <stdio.h>
#include <time.h>

#define LOG_FILE "application.log"
/**
 * @brief Retrieves the current timestamp as a formatted string.
 *
 * This helper function fills the provided buffer with the current date and time,
 * formatted as "YYYY-MM-DD HH:MM:SS".
 *
 * @param buffer Pointer to a character array where the timestamp will be stored.
 * @param size   The size of the buffer to ensure no overflow occurs.
 */
static void get_timestamp(char* buffer, size_t size) {
  time_t now = time(NULL);
  strftime(buffer, size, "%Y-%m-%d %H:%M:%S", localtime(&now));
}

/**
 * @brief Logs an error message to a log file and also prints it to stderr.
 *
 * This function writes a formatted error message to the log file specified by LOG_FILE,
 * prepending a timestamp and the "ERROR" label. It also prints the same error message
 * to the standard error stream (stderr) for immediate visibility.
 *
 * @param format The format string for the error message (printf-style).
 * @param ...    Additional arguments to be formatted into the message.
 *
 * @note The log file is opened in append mode. If the log file cannot be opened,
 *       an error message is printed to stderr and the function returns.
 */
void log_error(const char* format, ...) {
  FILE* log = fopen(LOG_FILE, "a");
  if (!log) {
    fprintf(stderr, "Error: Could not open log file.\n");
    return;
  }

  char timestamp[20];
  get_timestamp(timestamp, sizeof(timestamp));

  fprintf(log, "[%s] ERROR: ", timestamp);

  va_list args;
  va_start(args, format);
  vfprintf(log, format, args);
  va_end(args);

  fprintf(log, "\n");
  fclose(log);

  // Also print to stderr
  va_start(args, format);
  fprintf(stderr, "Error: ");
  vfprintf(stderr, format, args);
  fprintf(stderr, "\n");
  va_end(args);
}


/**
 * @brief Logs an event message to both a log file and standard output with a timestamp.
 *
 * This function formats and writes an event message to a log file specified by LOG_FILE,
 * as well as to the standard output (stdout). Each log entry is prepended with a timestamp.
 * The message format and arguments are specified in the same way as printf.
 *
 * @param format The format string for the event message (printf-style).
 * @param ...    Additional arguments to be formatted into the message.
 *
 * @note If the log file cannot be opened, an error is logged using log_error().
 * @note The timestamp is generated by get_timestamp().
 */
void log_event(const char* format, ...) {
  FILE* log = fopen(LOG_FILE, "a");
  if (!log) {
    log_error("Error: Could not open log file.\n");
    return;
  }

  char timestamp[20];
  get_timestamp(timestamp, sizeof(timestamp));

  fprintf(log, "[%s] EVENT: ", timestamp);

  va_list args;
  va_start(args, format);
  vfprintf(log, format, args);
  va_end(args);

  fprintf(log, "\n");
  fclose(log);

  fprintf(stdout, "[%s] EVENT: ", timestamp);
  va_start(args, format);
  vfprintf(stdout, format, args);
  va_end(args);
  fprintf(stdout, "\n");
}
